### ISSUE TITLE
react-0.13.0.js

### ISSUE THREAD

**Issue by udayms** [josebalius/ngReactGrid#76]
Hi Folks,

I wonder if anyone else faced this issue. I am getting errors if I try to use ngReactGrid with React v0.13.0.

The error I am getting is:
angular.min.js:93 TypeError: Cannot read property '__reactAutoBindMap' of undefined
    at Constructor (http://dragon.ak.fbcdn.net/hphotos-ak-xpa1/t39.3284-6/10734320_1571131556471061_497798403_n.js:5816:15)
    at NgReactGrid.render (file:///Users/udayms/pandoras-box/work/marketplace/mktp-symfony/web/bower/ngReactGrid/build/js/ngReactGrid.js:1178:55)
    at NgReactGrid.init (file:///Users/udayms/pandoras-box/work/marketplace/mktp-symfony/web/bower/ngReactGrid/build/js/ngReactGrid.js:882:10)
    at new NgReactGrid (file:///Users/udayms/pandoras-box/work/marketplace/mktp-symfony/web/bower/ngReactGrid/build/js/ngReactGrid.js:842:10)
    at link (file:///Users/udayms/pandoras-box/work/marketplace/mktp-symfony/web/bower/ngReactGrid/build/js/ngReactGrid.js:1678:13)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js:64:507
    at x (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js:55:69)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js:48:28)
    at x (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js:55:10)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.10/angular.min.js:48:28) <ng-react-grid grid="grid" class="ng-isolate-scope">

I also see a warning:
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory

To reproduce this error in the index.html in the examples folder, just change script src include from:
http://fb.me/react-0.10.0.js to http://fb.me/react-0.13.0.js

**Comment by josebalius** [comment]
@udayms Yeah I haven't tried react 0.13 with this project yet.....but thanks for letting me know of the issues i'll take a look

**Comment by guyjin** [comment]
Any progress on this?
